version: "3.8"

services:
  db_test:
    container_name: "health_log_test"
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
